### ISSUE TITLE
What is a "typical" team size and project duration?

### ISSUE THREAD

**Issue by jonblower** [swcarpentry/managing-research-software-projects#2]
I thought the lesson design looked great, but one thing that stood out for me was the "6x6" assumption - 6 people working together for 6 months. I guess everyone has a different experience, but for me this would be quite a large research software development project. In my own experience "2x3" or "2x6" (i.e. two people for 3-6 months) would be much more normal, and many projects are just one developer, plus some kind of management oversight.

I'd be interested to know if others feel the same way. One of my challenges as a manager is to find a methodology that gives benefits to a small team without adding too much overhead. But I think the list of tools (GitHub, Travis-CI, make, Sphinx) are a great set that add value even to small projects.

**Comment by duncanwp** [comment]
I would second that, 2x6 is more typical for the type of projects I've been involved with. If you're using Scrum or something similar it shouldn't make too much difference, but it does make it important to get the right sprint length and task size.

**Comment by timcnicholls** [comment]
I agree - I felt that the "6x6" size was an upper limit for a small/medium sized project rather than typical. The "small enough to meet for lunch" metric seemed an appropriate indicator tough.

My experience in software development for scientific instruments is that some projects are often smaller in team size but longer in duration ((e.g. several years or more) as they are interleaved with other aspects of the overall project. In that case many of the tools add value both in terms of team communication and in 'persistence' across intermittent phases of activity.

**Comment by jonblower** [comment]
+1. Although single-tasking is known to be more productive, it's a luxury we don't usually have! Most developers in my group will be working on >1 project at a time, with ebbs and flows of activity in each. I definitely agree with @timcnicholls that the use of these tools helps to manage this, as well as helping to pass on responsibilities to new developers.

**Comment by gvwilson** [comment]
Thanks all - actioned in #8.
